# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Doria Keung
email: doria.keung@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is Doria Keung's website and blog.
baseurl: ""
pages: ["hackbright",
       ]
twitter_username: doriaKeung
github_username:  doriable

# Build settings
markdown: kramdown
