# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Doria Keung
description: > # this means to ignore newlines until "baseurl:"
  This is Doria Keung's website and blog.
baseurl: ""
gems: [
        jekyll-paginate,
]
paginate: 5

# Contact information
email: doria.keung@gmail.com
twitter_username: doriaKeung
github_username: doriable
facebook_username: doria.keung
linkedin_username: doriakeung

# Build settings
markdown: kramdown
